run all oscap/anaconda tests on "Server with GUI" too
RHSecurityCompliance/contest pull request #11
Opened 2023-05-05 14:47 UTC by comps

The `2h` duration is there because the extra packages do add +20-30min of time, sometimes more.

2023-05-05 15:50 UTC, mildas commented
> To me, the with-gui case is a special case, and we could potentially have more like that, but the minimal installation is the baseline standard case

That's an interesting point. I always perceived them on same importance level. But Minimal as baseline and GUI as something extra is valid.

If we could come with ideas for more special cases as GUI (e.g. common machine configuration), then leaving code as it is now is fine to me.
Basically, I'd like to know that GUI won't be the only one with the extra hierarchy level. If it would be the only one, then we should consider different approaches, e.g. everything in `main.fmf`:
```
/hardening/oscap/ospp
/hardening/oscap/ospp (gui)
```

2023-05-05 16:15 UTC, comps commented
> If we could come with ideas for more special cases as GUI (e.g. common machine configuration)

Yeah, I can't think of anything right now. Multiple architectures maybe, but that would be done on a higher level.

> If it would be the only one, then we should consider different approaches, e.g. everything in `main.fmf`:

Okay, that should be possible.

It would look something like

```
...
environment+:
    PYTHONPATH: ../../lib
duration: 1h
extra-hardware: |
    keyvalue = HVM=1
    hostrequire = memory>=4800
...
/cis:
    environment+:
        PROFILE: cis
...
/with-gui:
    environment+:
        USE_SERVER_WITH_GUI: 1
    duration: 2h
    ...
    /cis:
        environment+:
            PROFILE: cis
    ...
```

2023-05-10 14:55 UTC, cortesana commented
My preference on this is to spread horizontally, i.e.:
```
/annocheck
/aslr-bits
/kernel/cmdline
...
```
rather than vertically, i.e.:
```
other/annocheck
other/aslr-bits
/kernel/cmdline
...
```
If further down the road there is an increase in the number of special cases on the same hierarchy and exploring the tests becomes a problem, this could easily be overcome by further classification of the cases into meaningful groups.

> Basically, I'd like to know that GUI won't be the only one with the extra hierarchy level. If it would be the only one, then we should consider different approaches, e.g. everything in `main.fmf`

I prefer the extra hierarchy level over everything being in `main.fmf`. @mildas What is the consideration behind not wanting GUI to be the only one with the extra hierarchy level?

2023-05-15 09:54 UTC, mildas commented
> What is the consideration behind not wanting GUI to be the only one with the extra hierarchy level?

Then we would have 2 very similar tests on 2 different hierarchy levels. Basically, an additional hierarchy level only because of extra packages that come with GUI. Roots of it probably come from my previous understanding of Minimal and GUI installations - considering them still as equivalent.

And at least knowing, there will be more test cases in the extra hierarchy level, would convince me it makes sense to have it. It would be more understandable also for others to see the difference.

2023-05-16 13:49 UTC, cortesana commented
Thanks, @mildas!

2023-05-17 11:16 UTC, mildas requested changes
CIS Server Lever 1 (`cis_server_l1`) and Level 2 (`cis`) shouldn't be enabled on GUI. OSPP and CUI can be tested with GUI only on RHEL9=<

See docs
- RHEL8 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/security_hardening/index#ref_profiles-not-compatible-with-server-with-gui_deploying-systems-that-are-compliant-with-a-security-profile-immediately-after-an-installation
- RHEL9 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/security_hardening/index#ref_profiles-not-compatible-with-server-with-gui_deploying-systems-that-are-compliant-with-a-security-profile-immediately-after-an-installation

2023-05-18 08:12 UTC, mildas commented on hardening/oscap/main.fmf
> +        because: exists only on RHEL-7
`doesn't exist on RHEL-7`

2023-05-19 10:36 UTC, mildas requested changes

2023-05-19 10:36 UTC, mildas commented on hardening/oscap/with-gui.fmf
> +        when: distro <= rhel-8
`distro == rhel-8`

2023-05-19 10:36 UTC, mildas commented on hardening/anaconda/with-gui.fmf
> +        when: distro <= rhel-8
`distro == rhel-8`

2023-05-19 14:31 UTC, mildas approved these changes
We have decided not to test OSPP with GUI on RHEL7.
Everything else was already LGTM.

2023-05-19 14:31 UTC, merged